# Generated by Django 4.2.20 on 2025-04-06 18:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=255)),
                ('shop_domain', models.CharField(blank=True, max_length=255, null=True)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('payload', models.JSONField()),
            ],
        ),
    ]
