# Generated by Django 4.2.20 on 2025-04-07 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_customer_customeraddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='shopify_id',
            field=models.BigIntegerField(default=-1, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customeraddress',
            name='shopify_id',
            field=models.BigIntegerField(default=-1, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customeraddress',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
