# Generated by Django 4.2.20 on 2025-04-07 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_customer_shopify_id_customeraddress_shopify_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeraddress',
            name='customer_shopify_id',
            field=models.BigIntegerField(default=-1, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customeraddress',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
